config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :artists do
    resources :songs, shallow: true
    # resources :songs, only: [:new, :create, :edit]
  end

  # resources :songs, only: [:show]
  root 'artists#index'
  # get '/songs', to: 'songs#index'
  resources :songs, only: [:index]
  resources :playlists


end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates_presence_of :name, :image_path
  validates_uniqueness_of :name

  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
  validates_presence_of :name
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  belongs_to :playlist
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.save ? (redirect_to @artist) : (render :new)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update_attributes(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end


end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
 def index
 end

 def new
   @playlist = Playlist.new
 end

 def create
   @playlist = Playlist.new(playlist_params)
   @playlist.save ? (redirect_to @playlist) : (render :new)
 end

 def show
   @playlist = Playlist.find(params[:id])

 end

 def edit
   @playlist = Playlist.find(params[:id])
 end

 def update
   @playlist = Playlist.find(params[:id])
   if @playlist.update_attributes(playlist_params)
     redirect_to @playlist
   else
     render :edit
   end
 end

private

 def playlist_params
   params.require(:playlist).permit(:name, song_ids: [])
 end


end

app/controllers/songs_controller.rb
 class SongsController < ApplicationController
  def index
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
    @artist = @song.artist
  end

  def update
    @song = Song.find(params[:id])
    @song.update_attributes(song_params)
    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
    @artist = Artist.find(@song[:artist_id])
  end

  # def destroy
  #
  # end

private

  def song_params
    params.require(:song).permit(:title)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artistform.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1><br>

<%= render "artistform" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% Artist.all.each do |artist|  %>
  <%= link_to artist[:name], artist_path(artist) %>
<% end  %><br>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1><br>

<%= render "artistform" %>

app/views/artists/show.html.erb
<h1> <%= @artist[:name] %> </h1>
<%= image_tag @artist.image_path %><br>
<ul>
  <h3>Songs:</h3>
  <% @artist.songs.order(:title).each do |song| %>
    <li><%= link_to song.title, song_path(@artist.songs.where(title: song.title).first) %></li>
    <% end %>
</ul>

<h5> <%= link_to "Add New Song", new_artist_song_path(@artist) %> </h5>
<h5> <%= link_to "Edit #{@artist.name} info", edit_artist_path %> </h5>
<h5> <%= link_to "Delete #{@artist.name}", artist_path(@artist), method: :delete %> </h5><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlists/_playlistform.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.text_field :name %>

  <% Song.all.each do |song| -%>
    <div>
      <%= check_box_tag :song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}" %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist <%= @playlist.name %> </h1>

<%= render "playlistform" %>

app/views/playlists/index.html.erb
<h1>Playlists</h1>
<% Playlist.all.each do |playlist| %>
  <%= link_to playlist.name, playlist_path(playlist) %>
<% end %>
<br>
<h4> <%= link_to "New Playlist", new_playlist_path %> </h4>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render "playlistform" %>

app/views/playlists/show.html.erb
<h2> <%= @playlist.name %> Playlist </h2>

<ul>
  <% @playlist.songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %> by <%= song.artist.name %> </li>
  <% end %>
</ul>
<h4> <%= link_to "Edit Playlist", edit_playlist_path %> </h4>
<h5> <%= link_to "All Playlists", playlists_path %> </h5>

app/views/songs/_form.html.erb
<p>Add song for <%= @artist.name %> </p>
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/_songform.html.erb
<p>Add song for <%= @artist.name %> </p>
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit <%= @song.title %> </h1>

<%= render "songform" %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<ul>
  <h3>Songs:</h3>
  <% Song.all.order(:title).each do |song| %>
    <li><%= link_to song.title, song_path(song) %></li>
    <% end %>
</ul>

app/views/songs/new.html.erb
<p>Add song for <%= @artist.name %> </p>
<%= form_for([@artist, @song]) do |f| %>
  <% if @song.errors.any? %>
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h3> <%= @song.title %> by <%= @artist.name %> </h3>
<h4> <%= link_to @artist.name, artist_path(@artist) %> </h4><br>
<h5> <%= link_to "Edit", edit_song_path(@song) %> </h5><br />